server:
  port: 8070

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer: http://localhost:9080/realms/ProtocolSN
          jwk-set-uri: http://localhost:9080/realms/ProtocolSN/protocol/openid-connect/certs

