spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/mydb
    username: postgres
    password: example
  liquibase:
    change-log: classpath:db/changelog/master.xml

logging:
  level:
    root: INFO