version: '1'

services:
  sampleService:
    image: flyway-migration:latest
    ports:
      - 8081:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - 5432:5432